import streamlit as st
# import requests

st.title("Voight Kampff")
st.image("https://m.economictimes.com/thumb/msid-66752021,width-1200,height-900,resizemode-4,imgsize-98420/robot-touch.jpg")
st.markdown("""
            :performing_arts:Rules: you will be randomly assign AI :vs: Human role, click play if you are ready.
            Players are secretly divided into two teams – humans and androids.
            Humans answer questions and then share them with the group.
            Androids are provided answers generated by a Deep Learning model and must convince the group they are human.
            Players have time to discuss and vote each other out.Users might all be human. They might all be androids. Each game is random.
            """, unsafe_allow_html=False)

# rule=
start = st.button("Play")
if start:
    st.balloons()
    st.write("game start")
    # request=requests.get(url).json()
    # # message=request[0]
    st.success("here is the message for you")
    with st.expander("check message"):
        st.write("""message1
             """)
    st.success("let's fool them")
